In [1]:
#Q1--
class empty:
    pass

In [2]:
class student:
    def __init__(self,name,roll):
        self.name = name
        self.roll = roll
    
I = student("Bhanu",21)
print(I.name)
I.name = "Ramu"
print(I.name)

Bhanu
Ramu


In [3]:
#Q2--
class cnvrt:
    def __init__(self,a):
        self.val = a
    def toDecimal(self):
        return int(self.val,16)
    
x = cnvrt('C77')
y=x.toDecimal()
print(y)


3191


In [4]:
#Q3-
class checker:
    def __call__(self,cl1,cl2):
        return issubclass(cl1,cl2)
    
class animal:
    pass

class dog(animal):
    pass

e = checker()
e(dog,animal)

True

In [5]:
#Q4--

class player:
    age = 32
    place = "Delhi"

    def show_place(self):
        print(f"place = {self.place}")
        return
    

class cricketer(player):
    def __init__(self,name,runs):
        self.name = name
        self.runs = runs
    def showdetails(self):
        print(f"player name = {self.name}")
        print(f"age = {player.age}")
        print(f"place = {super().place}")
        super().show_place()
        print(f"total runs = {self.runs}")

virat = cricketer("Virat",12000)
virat.showdetails()

player name = Virat
age = 32
place = Delhi
place = Delhi
total runs = 12000


In [6]:
#Q5--
class rectangle:
    def __init__(self,length,breadth) -> None:
        self.l = length
        self.b = breadth
    @property
    def area(self):
        return self.l*self.b
    
ract1 = rectangle(3,4)
print(f"area of the rectangle is {ract1.area}")

area of the rectangle is 12


In [7]:
#Q6--
class revrser:
    def __call__(self,string):
        return ' '.join(x[-1::-1] for x in string.split())
    
x = revrser()
x("my name is bhanu")


'ym eman si unahb'

In [8]:
#Q7--
class three_sum_zero:
    def __call__(self,l):
        n = len(l)
        ans = []
        i = 0
        for i in range(n):
            for j in range(i+1,n):
                for k in range(j+1,n):
                    if(l[i]+l[j]+l[k]==0):
                        ans.append([l[i],l[j],l[k]])
        return ans

x = three_sum_zero()
l = [-25, -10, -7, -3, 2, 4, 8, 10]
a = x(l)
print(a)


[[-10, 2, 8], [-7, -3, 10]]


In [9]:
#Q8--
#same as previous

In [10]:
import numpy as np
import pandas as pd


In [17]:
arr1 = [[10,40],
        [30,20]]

arr = np.array(arr1)

print(np.sort(arr1,axis=0))
print(np.sort(arr1,axis=1))
print(np.sort(arr.flatten()))

[[10 20]
 [30 40]]
[[10 40]
 [20 30]]
[10 20 30 40]


In [18]:
#Q10-
angles = np.array([0,30,45,60,90])
sines = np.array(list(np.sin(x*np.pi/180) for x in angles))
print("sines of the given angles are:\n",sines)
coses = np.array(list(np.cos(x*np.pi/180) for x in angles))
print("coses of the given angles are:\n",coses)
tans = np.array(list(np.tan(x*np.pi/180) for x in angles))
print("tans of the given angles are:\n",tans)


#OPTIMIZEWD APPROACH
print(np.sin(angles*np.pi/180))

sines of the given angles are:
 [0.         0.5        0.70710678 0.8660254  1.        ]
coses of the given angles are:
 [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tans of the given angles are:
 [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
[0.         0.5        0.70710678 0.8660254  1.        ]


In [19]:
#Q11-
arr = np.array(
 [[0,1,2],
 [3,4,5]]
)
print(min(len(arr[0]),len(arr)))
ans = sum(list(arr[x][x] for x in range(min(len(arr),len(arr[0])))))
print(ans)

#OPTIMIZED APPROACH
arr.trace()

2
4


4

In [2]:
#Q12--
import numpy as np
original = np.ones(25)
original.resize(5,5)
original2 = original.copy()
original3 = original.copy()
length = len(original)
width = len(original[0])

for i in range(length):
    for j in range(width):
        if(i==length-1 or j==width-1 or i==0 or j==0):
            original[i][j]=1
        else:
            original[i][j]=0

print(original)

#OR

original2[1:-1,1:-1] = np.zeros((original2.shape[0]-2,original2.shape[1]-2))
print(original2)


original3[1:-1,1:-1] = 0
print(original3)



[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
#Q13-
import sys
arr = np.array([1,2,3])

print("size of the array is:",arr.size)
print("Length of one array element:",arr.itemsize)
print("total size consumed by the array in meomory",arr.size*arr.itemsize)


size of the array is: 3
Length of one array element: 4
total size consumed by the array in meomory 12


In [23]:
arr1 = np.array([1,2,3,4])
arr2 = np.array(['Red',"Green","White","Orange"])
arr3 = np.array([12.20,15,20,40])

data = np.stack(arrays=[arr1,arr2,arr3],axis = 1)
print(data)

[['1' 'Red' '12.2']
 ['2' 'Green' '15.0']
 ['3' 'White' '20.0']
 ['4' 'Orange' '40.0']]


In [38]:
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1,3,5,7,9])

add = s1+s2
print(f"add : {add.values}")
print(f"subtract : {(s1-s2).values}")
print(f"multiply : {(s1*s2).values}")
np.set_printoptions(precision=2)
print(f"devide : {(s1/s2).values}")


add : [ 3  7 11 15 19]
subtract : [1 1 1 1 1]
multiply : [ 2 12 30 56 90]
devide : [2.   1.33 1.2  1.14 1.11]


In [39]:
arr = np.array([1,2,3,4,5])
srs = pd.Series(arr)

print(srs)

0    1
1    2
2    3
3    4
4    5
dtype: int32


In [55]:
dict1 = {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
df = pd.DataFrame(dict1)
df

X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

In [56]:
df.index.name = "X"
df.rename(columns={"Z":"","Y":"Z","X":"Y"},inplace = True)

df

Y   Z    
X            
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

In [58]:
dict1 = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura',
'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(dict1,index=labels,columns=['attempts','name','qualify','score'])
df


attempts       name qualify  score
a         1  Anastasia     yes   12.5
b         3       Dima      no    9.0
c         2  Katherine     yes   16.5
d         3      James      no    NaN
e         2      Emily      no    9.0
f         3    Michael     yes   20.0
g         1    Matthew     yes   14.5
h         1      Laura      no    NaN
i         2      Kevin      no    8.0
j         1      Jonas     yes   19.0

In [59]:
df.head(3)

attempts       name qualify  score
a         1  Anastasia     yes   12.5
b         3       Dima      no    9.0
c         2  Katherine     yes   16.5

In [63]:
df.head()


attempts       name qualify  score
a         1  Anastasia     yes   12.5
b         3       Dima      no    9.0
c         2  Katherine     yes   16.5
d         3      James      no    NaN
e         2      Emily      no    9.0

In [65]:
df.isnull().sum()

attempts    0
name        0
qualify     0
score       2
dtype: int64

In [68]:
df[df['score'].isnull()]

attempts   name qualify  score
d         3  James      no    NaN
h         1  Laura      no    NaN

In [71]:
filt = (df['score']>=15) & (df['score']<=20)
df[filt]

attempts       name qualify  score
c         2  Katherine     yes   16.5
f         3    Michael     yes   20.0
j         1      Jonas     yes   19.0

In [73]:
filt = (df['attempts']<=2) & (df['score']>15)
df[filt]

attempts       name qualify  score
c         2  Katherine     yes   16.5
j         1      Jonas     yes   19.0