In [42]:
import numpy as np

Array creation

In [43]:
#1) from a given python ds as list dict or tuple--
list1 = [4.5,2,3.24,6,3]
list2 = ['a','b','c']
list3 = [-2,9,-4,23,2]

arr1 = np.array(list1,dtype=int)
arr2 = np.array(list2,dtype=str)
arr3 = np.array(list3,dtype=np.uint)        #see the warning
print(arr1)
print(arr2)

[4 2 3 6 3]
['a' 'b' 'c']


C:\Users\Dev IIT\AppData\Local\Temp\ipykernel_8132\4033854867.py:8: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -2 to uint32 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arr3 = np.array(list3,dtype=np.uint)        #see the warning
C:\Users\Dev IIT\AppData\Local\Temp\ipykernel_8132\4033854867.py:8: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -4 to uint32 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arr3 = np.array(list3,dtype=np.uint)        #see the warning


In [44]:
#2) intrinsic array creation functions--
arr = np.arange(0,100,10)
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
arr = np.linspace(1,50,100)
arr

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [46]:
#2d arrays --
arr = np.eye(5,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
#to accesss the diagonal elements---
arr = np.eye(6)
np.diag(arr)

array([1., 1., 1., 1., 1., 1.])

In [48]:
#3) general ndarrays creation--
arr = np.zeros((5,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.ones((1,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.]])

In [50]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [51]:
#4) manupulating pre-existing arrays---
a = np.array([1,2,3,4,5,6])
b = a[2:]

print(b+1)

[4 5 6 7]


In [52]:
arr = np.array(
    [[1, 2, 5],
    [2,3,4],
    [5,4,5]]
)

print(arr[1:])
print(arr[1:,1:])

[[2 3 4]
 [5 4 5]]
[[3 4]
 [4 5]]


In [53]:
#joining two or more arrays---
a = np.ones((2,2))
b = np.eye(2)
c = np.zeros((2,2))
d = np.diag([-1,-1])

np.block([[a,b],[c,d]])


array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -1.,  0.],
       [ 0.,  0.,  0., -1.]])

In [54]:
np.hstack([a,b])

array([[1., 1., 1., 0.],
       [1., 1., 0., 1.]])

In [55]:
np.vstack([a,b])

array([[1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.]])

Indexing of the arrays

In [56]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[1:6:2]

array([2, 4, 6])

In [57]:
arr[-1::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [58]:
#advanced indexing ---
#accessing multiple elements together ---
x = np.arange(10,-1,-1)
x
print(x)
print(x[np.array([1,2,5,8])])

[10  9  8  7  6  5  4  3  2  1  0]
[9 8 5 2]


In [59]:
#advanced indexing on multidimension arrays

x = np.arange(35).reshape(5,7)

#here we give np.array that defines the row indices --
x[np.array([0,2,4])]


array([[ 0,  1,  2,  3,  4,  5,  6],
       [14, 15, 16, 17, 18, 19, 20],
       [28, 29, 30, 31, 32, 33, 34]])

In [60]:
#to access the second element from all of the specified rows --
x[np.array([0,2,4]),1]

array([ 1, 15, 29])

In [61]:
#to access the first element from row 1 and 3rd from row 3 and fifth from row 5 ---
x[np.array([0,2,4]),np.array([0,2,4])]

array([ 0, 16, 32])

In [62]:
y = np.array(
    [[1,-2,-4,3],
    [9,0,2,-1],
    [-2,-3,1,8]]
)

y[y<0]      #to get all the negative values


array([-2, -4, -1, -2, -3])

Overflowing errors

In [63]:
print(np.power(100, 8, dtype = np.int32))
print(np.power(100,8,dtype=np.int64))

1874919424
10000000000000000


Broadcasting

In [64]:
arr = np.array([1,2,3,4,5])
arr * 3         # here 3 is being stratched to make a an array of 5 elements then multiplication of the elements takes place---


array([ 3,  6,  9, 12, 15])

Copy and view

In [65]:
brr = arr
brr[0]=1000000
print(arr)      #thus brr is a view not a copy

crr = arr.copy()

[1000000       2       3       4       5]


In [66]:
#to check for a view or copy ---
print(brr.base is arr)    
print(arr.base) 
print(crr.base is arr)

False
None
False


In [70]:
a = np.array([1,2,3,4])
b = a.copy()
c = a[:]

print(c.base is a)
print(b.base is a)

True
False


In [69]:
original_array = np.array([1, 2, 3, 4, 5])


view_array = original_array[1:4]

# Create a copy of the array
copy_array = original_array.copy()

# Check if view_array is a view or a copy
if view_array.base is original_array:
    print("view_array is a view of original_array")
else:
    print("view_array is a copy of original_array")

# Check if copy_array is a view or a copy
if copy_array.base is original_array:
    print("copy_array is a view of original_array")
else:
    print("copy_array is a copy of original_array")

view_array is a view of original_array
copy_array is a copy of original_array


In [72]:
a = np.array([1,2,3,4,5,6,7,78])
a.reshape(2,4)      #doesn't really change the array
a

a.resize(2,4)       #really changes the dimensions
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7, 78]])

Mathematical operations

In [74]:
#adding the matrices---
a = np.array([1,2,3,4])
b = np.array([3,4,5,6])
np.add(a,b)

array([ 4,  6,  8, 10])

In [75]:
np.subtract(a,b)

array([-2, -2, -2, -2])

In [76]:
np.multiply(a,b)

array([ 3,  8, 15, 24])

In [78]:

np.divide(a,b)

array([0.33333333, 0.5       , 0.6       , 0.66666667])

In [79]:
np.remainder(a,b)

array([1, 2, 3, 4])

In [80]:
np.mod(a,b)

array([1, 2, 3, 4])

In [81]:
np.power(a,b)

array([   1,   16,  243, 4096])

In [83]:
angles = np.array([0,30,45,60,90])
np.sin(angles*np.pi/180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [84]:
a = [1.22,3.4,56,6.92034]
np.trunc(a)

array([ 1.,  3., 56.,  6.])

In [85]:
np.floor(a)

array([ 1.,  3., 56.,  6.])

In [86]:
np.ceil(a)

array([ 2.,  4., 56.,  7.])

In [88]:
np.round(a,2)

array([ 1.22,  3.4 , 56.  ,  6.92])

In [89]:
b = np.array([1,2,4,8,16,32])
print(np.log2(b))


[0. 1. 2. 3. 4. 5.]


In [90]:
print(np.log10(b))

[0.         0.30103    0.60205999 0.90308999 1.20411998 1.50514998]


In [94]:
#sum --- 
#NOTE -- sum gives the sum of all elements of the array bur addition gives the sum of corresponding elements




a = np.array([1,2,3,4,5])
b = np.array([10,11,12,13,14])

print(np.sum([a,b]))

75


In [95]:
print(np.sum([a,b],axis=0))

[11 13 15 17 19]


In [96]:
print(np.sum([a,b],axis=1))

[15 60]


In [97]:
#for commutative sum --
print(np.cumsum(a))

[ 1  3  6 10 15]


In [98]:
#prod()

#it gives the product of the elements --
#arguments are same as sum
print(np.prod(a))

120


In [100]:
#finding lcm --- 
print(np.lcm.reduce(a))

60


In [101]:
print(np.gcd.reduce(a))

1


In [102]:
print(np.sinh(np.pi/2))

2.3012989023072947


In [106]:
x=np.arctan(1)
x*180/np.pi

45.0

In [107]:
#to get only the unique values --- 
np.unique(np.array([1,1,2,2,2,3,4,5]))

array([1, 2, 3, 4, 5])

Statistical functions

In [108]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
print(np.amax(a))
print(np.amin(a))

9
2


In [111]:
print(np.amin(a,axis=0))

[2 4 3]


In [112]:
print(np.percentile(a,25,axis=0))

[2.5 4.  4. ]


In [113]:
print(np.median(a,axis=1))

[5. 4. 4.]


In [115]:
print(np.mean(a,axis=1))

[5. 5. 5.]


In [117]:
heights = [150,155,152,160,170]
np.var(heights)
np.std(heights)

7.1442284397967

Array operations

In [119]:
matrix = np.array(
    [[1,2,3],
     [1,4,9],
     [1,0,1]]

)

print(matrix.T)

[[1 1 1]
 [2 4 0]
 [3 9 1]]


In [120]:
idt = np.eye(3)

idt @ matrix

array([[1., 2., 3.],
       [1., 4., 9.],
       [1., 0., 1.]])

In [121]:
np.matmul(idt,matrix)

array([[1., 2., 3.],
       [1., 4., 9.],
       [1., 0., 1.]])